name: Fygplugin
version: '${project.version}'
main: com.fygcafe.fygplugin.Fygplugin
api-version: 1.19
authors: [ youtissoum ]
description: A plugin for the fyg cafe minecraft server
website: https://github.com/youtissoum/newfygplugin
commands:
  updatefygplugin:
    description: Update the plugin
    permission: fygplugin.update
    permission-message: You do not have permissions to update the plugin
  tickedrestart:
    description: restarts the server after a timer
    permission: bukkit.command.restart
    permission-message: You do not have permission to restart the server (don't try it L noob XD)